name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Import smoke test
        run: |
          python - <<'PY'
          import importlib
          import sys
          modules = [
            'dcrm_ai_diagnostics.src.api.main',
            'dcrm_ai_diagnostics.src.models.infer',
            'dcrm_ai_diagnostics.src.dashboard.app',
          ]
          for m in modules:
            importlib.import_module(m)
          print('Smoke imports OK')
          PY


